#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export HISTFILE="$XDG_DATA_HOME/history"
export BASHDOTDIR="$XDG_CONFIG_HOME/bash"
# export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="librewolf"

# If not running interactively, don't do anything
#[[ $- != *i* ]] && return

#[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "$BASHDOTDIR/bashrc" ] && source "$BASHDOTDIR/bashrc" 
