#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export HISTFILE="$XDG_DATA_HOME/history"
# export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
# export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="librewolf"
